config/routes.rb
Rails.application.routes.draw do
  resources :tellers
  resources :companies
  resources :countries
  get 'home/index'
  devise_for :users
  resources :users, only: [:index]
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/teller.rb
class Teller < ApplicationRecord
  attr_accessor :year, :month
  # user.tellers
  belongs_to :user
  # company.tellers
  belongs_to :company
  # country.tellers
  belongs_to :country
  # company_name
  delegate :name, to: :company, prefix: true
  # country_name
  delegate :name, to: :country, prefix: true

  # date uniqueness needs this
  before_validation :assign_country, :set_the_date
  # we can set this just before record gets saved
  before_save :set_opening_balance
  # now update the next entry
  after_save :update_next_entry

  # one entry per month per user
  # another user can have the same month entry
  # same user can never have duplicate rows for any month
  validates :date, uniqueness: { scope: :user_id, message: 'single entry per month allowed (per user)'}
  validates :cash_in, presence: true
  validates :cash_out, presence: true

  # always keep teller entries sorted by date
  default_scope { order(:date) }

  # balance value of this entry
  def balance
    opening.to_f + cash_in.to_f - cash_out.to_f
  end

  private

    def assign_country
      self.country_id = company&.country_id
    end

    # datetime field allows us to quickly sort and search
    # no additional heavy logic required to calculate previous/next entry
    def set_the_date
      self.date = DateTime.new(year.to_i, month.to_i) if year.present? && month.present?
    end

    def set_opening_balance
      self.opening = last_entry&.balance
    end

    # no validations. callbacks fired (chain reaction forward)
    def update_next_entry
      return if next_entry.nil?

      # this balance is the opening for the next entry
      next_entry.update_attributes(opening: balance)
    end

    # entry just before this one. maybe not previous month. any month before this
    def last_entry
      Teller.where('date < ?', date).last
    end

    # entry after this one. maybe not next month, any month after this
    def next_entry
      Teller.where('date > ?', date).first
    end
    
end

app/controllers/tellers_controller.rb
class TellersController < ApplicationController
  before_action :set_teller, only: [:show, :edit, :update, :destroy]

  # GET /tellers
  # GET /tellers.json
  def index
    # teller transactions for the current user (student) only
    @tellers = current_user.tellers
  end

  # GET /tellers/1
  # GET /tellers/1.json
  def show
  end

  # GET /tellers/new
  def new
    @teller = Teller.new
  end

  # GET /tellers/1/edit
  def edit
  end

  # POST /tellers
  # POST /tellers.json
  def create
    @teller = Teller.new(teller_params)

    respond_to do |format|
      if @teller.save
        format.html { redirect_to @teller, notice: 'Teller was successfully created.' }
        format.json { render :show, status: :created, location: @teller }
      else
        format.html { render :new }
        format.json { render json: @teller.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tellers/1
  # PATCH/PUT /tellers/1.json
  def update
    respond_to do |format|
      if @teller.update(teller_params)
        format.html { redirect_to @teller, notice: 'Teller was successfully updated.' }
        format.json { render :show, status: :ok, location: @teller }
      else
        format.html { render :edit }
        format.json { render json: @teller.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tellers/1
  # DELETE /tellers/1.json
  def destroy
    @teller.destroy
    respond_to do |format|
      format.html { redirect_to tellers_url, notice: 'Teller was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teller
      @teller = Teller.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def teller_params
      # allow :year and :month to save the :date
      # :date will allow us to sort and search quickly.
      # separate year/month fields will need extra logic.
      params.require(:teller).permit(
        :date, :opening, :cash_in, :cash_out,
        :user_id, :company_id, :country_id,
        :year, :month
      )
    end
end

app/helpers/tellers_helper.rb
module TellersHelper
end

app/views/tellers/_form.html.erb
<div class="card">
  <div class="card-body">
<%= form_with(model: teller, local: true) do |form| %>
  <% if teller.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(teller.errors.count, "error") %> prohibited this teller from being saved:</h2>

      <ul>
        <% teller.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :user_id, value: current_user&.id %>

  <div class="form-group">
    <%= form.label :year %>
    <%= form.number_field :year, class: "form-input" %>
  </div>

  <div class="form-group">
    <%= form.label :month %>
    <%= form.select :month, options_for_select((1..12).to_a), {}, class: "form-input" %>
  </div>
  
  <div class="form-group">
    <%= form.label :cash_in %>
    <%= form.number_field :cash_in %>
  </div>

  <div class="form-group">
    <%= form.label :cash_out %>
    <%= form.number_field :cash_out %>
  </div>

  <div class="form-group">
    <%= form.label :company_id %>
    <%= form.select :company_id, options_from_collection_for_select(current_user.companies, :id, :name) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
  </div>
</div>

app/views/tellers/edit.html.erb
<h1>Editing Teller</h1>

<%= render 'form', teller: @teller %>

<%= link_to 'Show', @teller %> |
<%= link_to 'Back', tellers_path %>

app/views/tellers/index.html.erb
<p id="notice"><%= notice %></p>

<% if Country.count.zero? %>

  <div class="d-flex justify-content-center">
    <h1>You do not have any country</h1>
  </div>
  <div class="d-flex justify-content-center">
    <h2>Company needs a country (requirement 4.)</h2>
  </div>
  <div class="d-flex justify-content-center">
    <%= link_to "Let's create a Country", new_country_path, class: "btn btn-primary" %>
  </div>

<% elsif current_user.companies.count.zero? %>

  <div class="d-flex justify-content-center">
    <h1>We need a company, at least</h1>
  </div>
  <div class="d-flex justify-content-center">
    <%= link_to "Let's create a Company", new_company_path, class: "btn btn-primary" %>
  </div>

<% else %>

<h1>Tellers</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Opening</th>
      <th>Cash in</th>
      <th>Cash out</th>
      <th>Company</th>
      <th>Country</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tellers.each do |teller| %>
      <tr>
        <td><%= teller.date %></td>
        <td><%= teller.opening %></td>
        <td><%= teller.cash_in %></td>
        <td><%= teller.cash_out %></td>
        <td><%= link_to teller.company_name, company_path(teller.company) %></td>
        <td><%= teller.country_name %></td>
        <td><%= link_to 'Show', teller %></td>
        <td><%= link_to 'Edit', edit_teller_path(teller) %></td>
        <td><%= link_to 'Destroy', teller, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teller', new_teller_path %>

<% end %>

app/views/tellers/new.html.erb
<h1>New Teller</h1>

<%= render 'form', teller: @teller %>

<%= link_to 'Back', tellers_path %>

app/views/tellers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @teller.date %>
</p>

<p>
  <strong>Opening:</strong>
  <%= @teller.opening %>
</p>

<p>
  <strong>Cash in:</strong>
  <%= @teller.cash_in %>
</p>

<p>
  <strong>Cash out:</strong>
  <%= @teller.cash_out %>
</p>

<p>
  <strong>Company:</strong>
  <%= @teller.company_name %>
  | <%= link_to 'Show company ledger', company_path(@teller.company), class: "btn btn-secondary" %>
</p>

<p>
  <strong>Country:</strong>
  <%= @teller.country_name %>
</p>

<%= link_to 'Edit', edit_teller_path(@teller) %> |
<%= link_to 'Back', tellers_path %>