config/routes.rb
Rails.application.routes.draw do
  resources :tellers
  resources :companies
  resources :countries
  get 'home/index'
  devise_for :users
  resources :users, only: [:index]
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
  # only in case of assignment, run our method
  attr_writer :country_name
  belongs_to :country
  belongs_to :user
  # quickly fetch all transactions for this company
  # company.tellers
  has_many :tellers
  # additional associations to roles and multipe users
  has_many :users_roles
  has_many :users, through: :users_roles
  has_many :roles, through: :users_roles

  # country_name works
  delegate :name, to: :country, prefix: true

  # company must be unique but only for the user
  # another user can also have the same company
  validates :name, uniqueness: { scope: :user_id, message: 'duplicates not allowed'}

  # WARN: this is only the assignment. persist in DB as needed
  def country_name=(name)
    self.country = Country.find_or_create_by(name: name)
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  # just auto-fetch the company record for action
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    # we need companies of the current user only (student)
    @companies = current_user.companies.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        # show the list of companies directly. one less step.
        format.html { redirect_to companies_path, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def company_params
      # allow company and user association to be accepted
      params.require(:company).permit(:name, :country_id, :user_id, :country_name)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<div class="card">
<div class="card-body">
<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
        <% company.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :user_id, value: current_user&.id %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :country_name %>
    <%= form.select :country_name, options_for_select(Country::NAMES, form.object.country_name), {}, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>
</div>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<% if Country.count.zero? %>

  <div class="d-flex justify-content-center">
    <h1>You do not have any country</h1>
  </div>
  <div class="d-flex justify-content-center">
    <h2>Company needs a country (requirement 4.)</h2>
  </div>
  <div class="d-flex justify-content-center">
    <%= link_to "Let's create a Country", new_country_path, class: "btn btn-primary" %>
  </div>

<% else %>

<h1>Companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Country</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.country_name %></td>
        <td><%= link_to 'Create a teller entry', new_teller_path, class: "btn btn-secondary" %></td>
        <td><%= link_to 'Show ledger', company, class: "btn btn-secondary" %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

<% end %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Country:</strong>
  <%= @company.country_name %>
</p>

<% if @company.tellers.count.positive? %>
  <h3>Tellers</h3>
  <table class="table">
    <thead>
    <tr>
      <th>Year</th>
      <th>Month</th>
      <th>Opening</th>
      <th>In</th>
      <th>Out</th>
      <th>Balance</th>
      </tr>
    </thead>
    <tbody>
      <% @company.tellers.find_each do |teller| %>
        <tr>
          <td><%= teller.date.year %></td>
          <td><%= teller.date.month %></td>
          <td><%= teller.opening %></td>
          <td><%= teller.cash_in %></td>
          <td><%= teller.cash_out %></td>
          <td><%= teller.balance %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<%= link_to 'New Teller entry', new_teller_path, class: "btn btn-primary" %>
<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>