config/routes.rb
Rails.application.routes.draw do
  resources :tellers
  resources :companies
  resources :countries
  get 'home/index'
  devise_for :users
  resources :users, only: [:index]
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Ram, RamOnRails.in">
    <title>Cash Management Demo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%#  Bootstrap CSS %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%# font awesome %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>
  <body>
    <div class="full-width">
      <div class="d-flex w-100 h-100 p-3 flex-column">
        <header class="masthead <%= 'mb-auto' if request.path == root_path %>">
          <div class="inner navbar">
            <h3 class="masthead-brand">
              <%= link_to root_path do %>
                <i class="fa fa-home"></i>
              <% end %>
            </h3>
            <nav class="nav nav-masthead">
            <% if user_signed_in? %>
              <% if current_user.has_role?(:student) %>
              <a class="nav-link <%= 'active' if request.path == users_path %>" href= <%= users_path %> >Users</a>
              <a class="nav-link <%= 'active' if request.path == countries_path %>" href= <%= countries_path %> >Countries</a>
              <a class="nav-link <%= 'active' if request.path == companies_path %>" href= <%= companies_path %> >Companies</a>
              <a class="nav-link <%= 'active' if request.path == tellers_path %>" href= <%= tellers_path %> >Tellers</a>
              <% else %>
                <span class="navbar-text">Menu for Teacher</span>
              <% end %>
            <% else %>
              <span class="navbar-text">(Menu visible after -> Start)</span>
            <% end %>
            </nav>
            <nav class="nav nav-masthead justify-content-end">
              <% if user_signed_in? %>
                <%= link_to "Finish", destroy_user_session_path, method: :delete, class: "nav-link" %>
              <% else %>
                <%= link_to "Start", new_user_session_path, class: "nav-link" %>
              <% end %>
            </nav>
          </div>
          <div class="d-flex justify-content-center">
              <%= current_user.display_name if user_signed_in? %>
          </div>
          <div class="d-flex justify-content-center">
            <div id="notice"><%= notice %></div>
          </div>
        </header>

        <%= yield %>
        
        <footer class="mastfoot mt-auto">
          <div class="inner">
            <p>Sample by Ram, <a href="http://www.RamOnRails.in">RamOnRails.in</a></p>
          </div>
        </footer>
      </div>
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Ram, RamOnRails.in">
    <title>Cash Management Demo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>
  <body>
    <div class="full-width">
      <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
        <header class="masthead mb-auto">
          <div class="inner">
            <h3 class="masthead-brand"><%= link_to 'Home', root_path %></h3>
            <nav class="nav nav-masthead justify-content-center">
              <a class="nav-link <%= 'active' if request.path == users_path %>" href= <%= users_path %> >Users</a>
              <a class="nav-link <%# 'active' if request.path == companies_path %>" href="#">Companies</a>
              <a class="nav-link <%# 'active' if request.path == transactions_path %>" href="#">Transactions</a>
            </nav>
            <nav class="nav justify-content-end">
              <% if user_signed_in? %>
                <%= link_to "Leave", destroy_user_session_path, method: :delete, class: "nav-link" %>
              <% else %>
                <%= link_to "Start", new_user_session_path, class: "nav-link" %>
              <% end %>
            </nav>
          </div>
        </header>
        <%= yield %>
        <footer class="mastfoot mt-auto">
          <div class="inner">
            <p>Sample by Ram, <a href="http://www.RamOnRails.in">RamOnRails.in</a></p>
          </div>
        </footer>
      </div>
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>